name: 🔄 Update Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  regen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Linktree README
        run: node ./.github/scripts/generate-linktree.js

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          git diff --quiet || git commit -m "chore: regenerate linktree with images"
          git push
